In [1]:
#df = transactions[(transactions["month"]==9 & transactions["year"]==2014)]

In [18]:
import numpy as np
import pandas as pd

## Simple way of making an array

In [7]:
a1 = np.array([1,2,4,7])
a1

array([1, 2, 4, 7])

In [11]:
a2 = np.array([[1,23,54,12],[56,89,11,90]])

In [12]:
a2

array([[ 1, 23, 54, 12],
       [56, 89, 11, 90]])

In [21]:
a2.size

8

# 1. Make an Array
### 1.1  Making a random array with `randn`

In [3]:
arr = np.random.randn(5,4)

In [4]:
arr

array([[-0.87937824,  0.79580391,  0.5705195 ,  0.51905766],
       [-1.46139608, -0.59723356,  0.29802752, -0.03169795],
       [-0.33578691,  1.04107366, -0.84574517, -0.06918183],
       [-1.29850118, -0.67307093,  1.15254396,  0.57516916],
       [ 1.65543641, -1.16459994,  1.0537147 , -0.32614776]])

In [5]:
arr.shape

(5, 4)

## 1.2 Making a `1-D`random array with `arange()`

In [6]:
range_array = np.arange(1,10,1)
range_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.3 Making a `n-dim` array with `randint()`

In [30]:
a4 = np.random.randint(1,10,size=(2,3,2))

In [31]:
a4

array([[[9, 1],
        [1, 9],
        [8, 1]],

       [[4, 3],
        [4, 5],
        [2, 8]]])

In [33]:
a4[:1,1:2,1:2]

array([[[9]]])

In [19]:
df = pd.DataFrame({"Fruit":["Apples","Banana"],"Colour":["Red","Yellow"]})

## 1.4 Making an array with `random()`
#### To  get random numbers b/n 0 & 1

In [39]:
np.random.seed(42)
a5 = np.random.random((5,3))

In [40]:
a5

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

## 1.5 Making an array with `rand()`
Returns sample values from a univariate normal distribution

In [41]:
a6 = np.random.randn(5,3)

In [42]:
a6

array([[-0.57138017, -0.92408284, -2.61254901],
       [ 0.95036968,  0.81644508, -1.523876  ],
       [-0.42804606, -0.74240684, -0.7033438 ],
       [-2.13962066, -0.62947496,  0.59772047],
       [ 2.55948803,  0.39423302,  0.12221917]])

In [45]:
i = np.argsort(a5)

In [46]:
i

array([[0, 2, 1],
       [2, 1, 0],
       [0, 2, 1],
       [1, 0, 2],
       [2, 1, 0]])

---

## 2. `reshape()`

In [47]:
a5

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [50]:
a5.shape

(5, 3)

In [51]:
a5.reshape(3,5)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

---

## 3. `argsort()` 
Returns an array with indexes of same shape as the array in the order of elements getting sorted

In [52]:
a7 = np.array([97,23,1,10])

In [56]:
a7.argsort()

array([2, 3, 1, 0])

---

## 4. `linspace`

In [57]:
x = np.linspace(0,10,100)

In [58]:
x

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [59]:
a5

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

---

## 5.`argmax`
Returns the index of the highest element in the array

In [64]:
x = np.array([1,32,54,10])
np.argmax(x)

2

In [68]:
demo = np.random.randint(1,10,size=(2,3,3))

In [69]:
demo

array([[[5, 9, 7],
        [2, 4, 9],
        [2, 9, 5]],

       [[2, 4, 7],
        [8, 3, 1],
        [4, 2, 8]]])

In [71]:
demo.reshape(3,6)

array([[5, 9, 7, 2, 4, 9],
       [2, 9, 5, 2, 4, 7],
       [8, 3, 1, 4, 2, 8]])

### Broadcasting
What is broadcasting?

Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data. This saves time and space. For example, if you have a 3x3 array (A) and want to add a 1x3 array (B), NumPy will add the row of (B) to every row of (A).

Rules of Broadcasting

If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
---
If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
---
## If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
The broadcasting rule: In order to broadcast, the size of the trailing axes for both arrays in an operation must be either the same size or one of them must be one.
---

---

## 6. Turning an image into numpy array

In [74]:
from matplotlib.image import imread

dog = imread("../images/numpy-dog-photo.png")

---

In [ ]:
https://numpy.org/doc/1.18/reference/index.html